// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: countries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (
  code, name, continent_name
) VALUES (
  $1, $2, $3
)
RETURNING code, name, continent_name
`

type CreateCountryParams struct {
	Code          int32
	Name          pgtype.Text
	ContinentName pgtype.Text
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry, arg.Code, arg.Name, arg.ContinentName)
	var i Country
	err := row.Scan(&i.Code, &i.Name, &i.ContinentName)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM countries
WHERE code = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, code int32) error {
	_, err := q.db.Exec(ctx, deleteCountry, code)
	return err
}

const getCountry = `-- name: GetCountry :one
SELECT code, name, continent_name FROM countries
WHERE code = $1 LIMIT 1
`

// COUNTRIES
func (q *Queries) GetCountry(ctx context.Context, code int32) (Country, error) {
	row := q.db.QueryRow(ctx, getCountry, code)
	var i Country
	err := row.Scan(&i.Code, &i.Name, &i.ContinentName)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT code, name, continent_name FROM countries
ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(&i.Code, &i.Name, &i.ContinentName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountry = `-- name: UpdateCountry :exec
UPDATE countries
SET name = $2,
    continent_name = $3
WHERE code = $1
`

type UpdateCountryParams struct {
	Code          int32
	Name          pgtype.Text
	ContinentName pgtype.Text
}

func (q *Queries) UpdateCountry(ctx context.Context, arg UpdateCountryParams) error {
	_, err := q.db.Exec(ctx, updateCountry, arg.Code, arg.Name, arg.ContinentName)
	return err
}
