// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchants.sql

package db

import (
	"context"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (
  merchant_name, country_code, admin_id
) VALUES (
  $1, $2, $3
)
RETURNING id, merchant_name, country_code, created_at, admin_id
`

type CreateMerchantParams struct {
	MerchantName string
	CountryCode  int32
	AdminID      int32
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant, arg.MerchantName, arg.CountryCode, arg.AdminID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.CountryCode,
		&i.CreatedAt,
		&i.AdminID,
	)
	return i, err
}

const deleteMerchant = `-- name: DeleteMerchant :exec
DELETE FROM merchants
WHERE id = $1
`

func (q *Queries) DeleteMerchant(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMerchant, id)
	return err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, merchant_name, country_code, created_at, admin_id FROM merchants
WHERE id = $1 LIMIT 1
`

// MERCHANTS
func (q *Queries) GetMerchant(ctx context.Context, id int64) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.CountryCode,
		&i.CreatedAt,
		&i.AdminID,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, merchant_name, country_code, created_at, admin_id FROM merchants
ORDER BY merchant_name
`

func (q *Queries) ListMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Merchant{}
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.MerchantName,
			&i.CountryCode,
			&i.CreatedAt,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchant = `-- name: UpdateMerchant :exec
UPDATE merchants
SET merchant_name = $2,
    country_code = $3,
    admin_id = $4
WHERE id = $1
`

type UpdateMerchantParams struct {
	ID           int64
	MerchantName string
	CountryCode  int32
	AdminID      int32
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error {
	_, err := q.db.Exec(ctx, updateMerchant,
		arg.ID,
		arg.MerchantName,
		arg.CountryCode,
		arg.AdminID,
	)
	return err
}
