// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Currency string

const (
	CurrencyUSD Currency = "USD"
	CurrencyEUR Currency = "EUR"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency
	Valid    bool // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type Account struct {
	ID          int64
	Owner       string
	Balance     int64
	Currency    string
	CountryCode int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Country struct {
	Code          int32
	Name          pgtype.Text
	ContinentName pgtype.Text
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative
	Amount    int64
	CreatedAt pgtype.Timestamptz
}

type Merchant struct {
	ID           int64
	MerchantName string
	CountryCode  int32
	CreatedAt    pgtype.Timestamptz
	AdminID      int32
}

type Order struct {
	ID        int32
	UserID    pgtype.Int4
	Status    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type OrderItem struct {
	OrderID   pgtype.Int4
	ProductID int32
	Quantity  pgtype.Int4
}

type Product struct {
	ID         int32
	Name       string
	MerchantID int32
	Price      pgtype.Int4
	Status     pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Tranfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be positive
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
