// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (
  order_id, product_id, quantity
) VALUES (
  $1, $2, $3
)
`

type CreateOrderItemParams struct {
	OrderID   pgtype.Int4
	ProductID int32
	Quantity  pgtype.Int4
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items
WHERE order_id = $1
  AND product_id = $2
`

type DeleteOrderItemParams struct {
	OrderID   pgtype.Int4
	ProductID int32
}

func (q *Queries) DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, arg.OrderID, arg.ProductID)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT order_id, product_id, quantity FROM order_items
WHERE order_id = $1
`

// Order Items (no primary key → composite operations)
func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.Int4) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(&i.OrderID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :exec
UPDATE order_items
SET quantity = $3
WHERE order_id = $1
  AND product_id = $2
`

type UpdateOrderItemParams struct {
	OrderID   pgtype.Int4
	ProductID int32
	Quantity  pgtype.Int4
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error {
	_, err := q.db.Exec(ctx, updateOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}
