// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  id, name, merchant_id, price, status
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, merchant_id, price, status, created_at
`

type CreateProductParams struct {
	ID         int32
	Name       string
	MerchantID int32
	Price      pgtype.Int4
	Status     pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.MerchantID,
		arg.Price,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MerchantID,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, merchant_id, price, status, created_at FROM products
WHERE id = $1 LIMIT 1
`

// PRODUCTS
func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MerchantID,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listProductsByMerchant = `-- name: ListProductsByMerchant :many
SELECT id, name, merchant_id, price, status, created_at FROM products
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProductsByMerchant(ctx context.Context, merchantID int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MerchantID,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = $2,
    merchant_id = $3,
    price = $4,
    status = $5
WHERE id = $1
`

type UpdateProductParams struct {
	ID         int32
	Name       string
	MerchantID int32
	Price      pgtype.Int4
	Status     pgtype.Text
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.MerchantID,
		arg.Price,
		arg.Status,
	)
	return err
}
