// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteCountry(ctx context.Context, code int32) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteMerchant(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id int32) error
	DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error
	DeleteProduct(ctx context.Context, id int32) error
	DeleteTransfer(ctx context.Context, id int64) error
	// ACCOUNTS
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	// COUNTRIES
	GetCountry(ctx context.Context, code int32) (Country, error)
	// ENTRIES
	GetEntry(ctx context.Context, id int64) (Entry, error)
	// MERCHANTS
	GetMerchant(ctx context.Context, id int64) (Merchant, error)
	// ORDERS
	GetOrder(ctx context.Context, id int32) (Order, error)
	// PRODUCTS
	GetProduct(ctx context.Context, id int32) (Product, error)
	// TRANSFERS
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListCountries(ctx context.Context) ([]Country, error)
	ListEntriesByAccount(ctx context.Context, accountID int64) ([]Entry, error)
	ListMerchants(ctx context.Context) ([]Merchant, error)
	// Order Items (no primary key → composite operations)
	ListOrderItems(ctx context.Context, orderID pgtype.Int4) ([]OrderItem, error)
	ListOrdersByUser(ctx context.Context, userID pgtype.Int4) ([]Order, error)
	ListProductsByMerchant(ctx context.Context, merchantID int32) ([]Product, error)
	ListTransfers(ctx context.Context) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) error
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
